"""
This script contains function that generate trials_df and events_df preprocessed data structures.

Author: @peterdoohan
"""

# %% Imports
import json
import numpy as np
import pandas as pd

# %% Global variables


# %% Main Functions
def get_events_df(session_dir):
    """Creates a dataframe with all states and events from a pycontrol session"""
    session_df = load_session_dataframe(session_dir.pycontrol_path, pair_end_suffix="_out")
    # remove rsync and print variable events
    events_df = session_df[
        (session_df.subtype != "sync") & (session_df.type != "info") & (session_df.type != "variable")
    ]
    events_df.reset_index(drop=True, inplace=True)
    return events_df


def get_trials_df(session_dir):
    """
    Creates a dataframe with all trial events from raw pycontrol data (path input).

    Rows of the output dataframe are:
    - trial(int): trial number
    - goal(str, alphanumerical): goal location active during trial
    - errors(int): number of non-goal ports poked during trial, see _get_errors function for more details
    - time, cue (float): time of cue onset
    - time, reward (float): time of reward delivery
    - time, end_reward_consumption (float): time of last poke out of reward port (can be after start of next trial)
    - time, ITI_start (float): time of ITI onset
    - time, trial_end (float): time of next trial
    """
    session_df = load_session_dataframe(session_dir.pycontrol_path)
    session_end_time = session_df.time.iloc[-1]
    print_variables_df = pd.DataFrame(session_df[session_df.subtype == "print"].content.to_list())
    stim_trials = print_variables_df.stim_trial.astype(bool)
    # calc trials since stim
    stim_group = stim_trials.cumsum()
    trials_since_stim = stim_group.groupby(stim_group).cumcount()
    trials_since_stim[stim_trials] = np.nan
    trials_since_stim[stim_group == 0] = np.nan  # before first stim trial
    # calc consecutive stim trials
    _groups = (stim_trials != stim_trials.shift()).cumsum()
    consecutive_stim_trials = stim_trials.groupby(_groups).cumsum().where(stim_trials, np.nan)
    # get stim times
    stim_start_times = [i / 1000 if i is not None else np.nan for i in print_variables_df.stim_start_time]  # seconds
    stim_end_times = [i / 1000 if i is not None else np.nan for i in print_variables_df.stim_end_time]  # seconds
    goals = print_variables_df.current_goal
    cue_times = session_df[session_df.content == "cue"].time.values
    reward_times = session_df[session_df.content == "reward"].time.values
    ITI_times = session_df[session_df.content == "ITI"].time.values[1:]  # session starts in ITI
    if len(cue_times) == len(reward_times) and len(cue_times) - 1 == len(ITI_times):
        ITI_times = np.append(ITI_times, session_end_time)
    elif len(cue_times) > len(ITI_times):
        cue_times = cue_times[:-1]
    trials_df = pd.DataFrame(
        {
            ("trial", ""): np.arange(1, len(cue_times) + 1),
            ("stim_trial", ""): stim_trials,
            ("trials_since_stim", ""): trials_since_stim,
            ("consecutive_stim_trials", ""): consecutive_stim_trials,
            ("goal", ""): print_variables_df.current_goal,
            ("errors", ""): _get_errors(session_df, goals, cue_times, reward_times),
            ("time", "stim_start"): stim_start_times,
            ("time", "cue"): cue_times,
            ("time", "stim_end"): stim_end_times,
            ("time", "reward"): reward_times,
            ("time", "end_reward_consumption"): _get_end_reward_consumption_times(
                session_df, goals, cue_times, reward_times, ITI_times, session_end_time
            ),
            ("time", "ITI_start"): ITI_times,
            ("time", "trial_end"): _get_trial_end_times(cue_times, ITI_times, session_end_time),
        }
    )
    trials_df.columns = pd.MultiIndex.from_tuples(trials_df.columns)
    return trials_df


# %% Supporting Functions


def load_session_dataframe(file_path, paired_events={}, pair_end_suffix=None):
    """
    Adapted from pycontrol data import module @ThomasAkam

    Generate a pandas dataframe from a pyControl data file (.txt or .tsv) containing
    the sessions data.  The resulting dataframe has the same columns as .tsv data files,
    see https://pycontrol.readthedocs.io/en/latest/user-guide/pycontrol-data/ for
    more information.  The only differences between Dataframes generated by loading
    a pyControl tsv file using pandas.read_csv() and this function are that using this
    function converts the json formatted string representation of variable values
    into Python dicts, adds a 'duration' column, and provides functionallity for handling
    events that come in pairs like pressing and releasing a lever (see below).
    The data frame has columns:

    time : The time the row occurred since the session start (seconds)
    type : Whether the row contains session 'info', a 'state' entry,
          'event', 'print' line, 'variable' values, 'error's or 'warnings's.
    subtype: The operation that generated the row, see docs link above.
    content : The name of the state, event or session information in the row,
              or value of variables and print lines.
    duration : The duration of states and paired events (see below).

    Optionally events can be specified as coming in pairs corresponding to the
    start and end of an action, e.g. entering and exiting a nosepoke. When a
    start-event end-event pair occurs in the data, only the start_event generates
    a row in the dataframe, with the end event used to compute the duration.

    Parameters
    ----------
    file_path : path to pyControl data file.

    paired_events : Optional dict specifying paired events e.g.
                    {'poke_1_in':poke_1_out', 'poke_1_in':poke_1_out'}.

    pair_end_suffix : Optional string specifying a suffix used to indicate the
                      end event of paired events that share a common stem e.g.
                      the pair {'poke_1_in':poke_1_out'} would be found
                      automatically using pair_end_suffix='_out'

    Returns
    -------
    df : session dataframe
    """
    # Load data from file.

    df = pd.read_csv(file_path, delimiter="\t")
    # Convert variables row value fields to dicts from json strings.
    df.loc[df["type"] == "variable", "content"] = df.loc[df["type"] == "variable", "content"].apply(json.loads)

    # Add state durations.
    df.loc[df["type"] == "state", "duration"] = -df.loc[df["type"] == "state", "time"].diff(-1)

    # Find paired events with specified pair end suffix.
    if pair_end_suffix:
        event_names = set(df.loc[df.type == "event", "content"])
        end_events = [ev for ev in event_names if ev.endswith(pair_end_suffix)]
        for end_event in end_events:
            stem = end_event[: -len(pair_end_suffix)]
            try:
                start_event = next(ev for ev in event_names if ev.startswith(stem) and ev != end_event)
            except StopIteration:
                continue  # No matching start event found.
            paired_events[start_event] = end_event

    # Compute paired event durations and remove end events.
    if paired_events:
        end2start = {v: k for k, v in paired_events.items()}
        start_times = {se: None for se in paired_events.keys()}
        start_inds = {se: None for se in paired_events.keys()}
        end_inds = []
        for i in df.index:
            if not df.loc[i, "type"] == "event":
                continue
            if df.loc[i, "content"] in paired_events.keys():  # Pair start event.
                start_times[df.loc[i, "content"]] = df.loc[i, "time"]
                start_inds[df.loc[i, "content"]] = i
            elif df.loc[i, "content"] in paired_events.values():  # Pair end event.
                start_event = end2start[df.loc[i, "content"]]
                if start_times[start_event] is not None:
                    df.loc[start_inds[start_event], "duration"] = df.loc[i, "time"] - start_times[start_event]
                    start_times[start_event] = None
                    end_inds.append(i)
        df.drop(index=end_inds, inplace=True)

    # Reset index and set column order.
    df.reset_index(drop=True)
    df = df.reindex(columns=["time", "type", "subtype", "content", "duration"])
    return df


def get_print_variables_df(session_df):
    """Transforms printed dictionaries in pycontrol raw data into a dataframe with columns
    for each key-value pair"""
    print_variables = session_df[session_df.subtype == "print"].content.to_list()
    return pd.DataFrame(print_variables)


def _get_errors(session_df, goals, cue_times, reward_times, next_poke_threshold=3):
    """Returns number of errors made on each trial.
    Errors are defined as pokes into no-goal ports after the cue onset and before the reward delivery. A threshold
    is used to define the maximum time between two pokes to be considered as the same poke (subthreshold = same error).
    """
    n_errors = []
    for goal, cue_time, reward_time in zip(goals, cue_times, reward_times):
        non_goal_in_events = [  # get all poke out events in current trial + before next trial ends
            event
            for event in session_df[session_df.type == "event"].itertuples()
            if (event.time > cue_time)
            and (event.time < reward_time)
            and (event.content[-2:] == "in")
            and not (event.content[:2] == goal)
        ]
        if len(non_goal_in_events) == 0:
            n_errors.append(0)
        else:
            errors = [non_goal_in_events[0]]
            for i in np.arange(0, len(non_goal_in_events) - 1):
                current_error = non_goal_in_events[i]
                next_error = non_goal_in_events[i + 1]
                if (current_error.content == next_error.content) and (
                    next_error.time - current_error.time < next_poke_threshold
                ):
                    continue
                else:
                    errors.append(current_error)
            n_errors.append(len(errors))
    return n_errors


def _get_end_reward_consumption_times(
    session_df, goals, cue_times, reward_times, ITI_times, session_end_time, next_poke_threshold=3
):
    """Gets time animal finishes consuming reward at the goal location.
    - Calculated by looping over trials to get the time when the subject last poked out of the reward port before
      triggering the next reward
    - In cases where there is no poke-out registered from the reward port (leading to an IndexError) end of ITI time
      (=start of the next trial) is taken as the end of reward consumption
    """
    end_reward_consumption_times = []
    for goal, cue_time, ITI_time, next_rew_time in zip(
        goals,
        cue_times,
        np.append(ITI_times, session_end_time),
        np.append(reward_times, session_end_time)[1:],
    ):
        goal_out_events = [  # get all poke out events in current trial + before next trial ends
            event
            for event in session_df[session_df.type == "event"].itertuples()
            if (event.time > cue_time) and (event.time < next_rew_time) and (event.content == goal + "_out")
        ]
        # impose maximum time between reward poke out to avoid long RC periods
        try:
            filtered_goal_out_events = [goal_out_events[0]]
            for i in range(1, len(goal_out_events)):
                if goal_out_events[i].time - filtered_goal_out_events[-1].time > next_poke_threshold:
                    break
                filtered_goal_out_events.append(goal_out_events[i])
            end_reward_consumption_times.append(filtered_goal_out_events[-1].time)
        except IndexError:  # Poke out event was not registered, use start of ITI instead.
            end_reward_consumption_times.append(ITI_time)
    return np.array(end_reward_consumption_times)


def _get_trial_end_times(cue_times, ITI_times, session_end_time):
    """Gets trial end times (= start time of next trial)"""
    end_trial_times = cue_times[1:]  # define as start of next trial
    if ITI_times[-1] > cue_times[-1]:
        end_trial_times = np.append(end_trial_times, session_end_time)
    return end_trial_times


# %% other pycontrol processing functions


def get_pycontrol_sync_times(pycontrol_path):
    """
    Function to extract sync times from pycontrol data.
    Args:
        pycontrol_path (Path): Path to pycontrol data file
    Returns:
        sync_times (np.array): Array of sync times in seconds
            from start of session
    """
    raw_pycontrol_df = pd.read_csv(pycontrol_path, sep="\t")
    return raw_pycontrol_df[raw_pycontrol_df["subtype"] == "sync"].time.to_numpy()


# %% Dev
